version: '3.6'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgresdb:
    build:
      context: ./core/src/main/resources/db/schema/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "root"
      POSTGRES_DB: "postgres"

