version: '3'
services:
  postgres:
    image: db
    container_name: postgres-interview-db
    network_mode: bridge
    build:
      context: ./core/src/main/resources/db/schema
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: brainweb
      POSTGRES_PASSWORD: brainweb
      POSTGRES_DB: postgres
  server:
    image: docker-interview-test
    container_name: interview-spring-boot-application
    network_mode: bridge
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres