version: "3.7"
services:
    spring-app:
      build:
        context: .
        dockerfile: ./core/src/main/docker/Dockerfile
      ports:
        - "8080:8080"
    postgres-app:
      build: ./core/src/main/resources/db/schema
      ports:
        - "5432:5432"
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      depends_on:
        - postgres-app
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin
        - PGADMIN_DEFAULT_PASSWORD=admin
        - PGADMIN_LISTEN_PORT=5050
      ports:
        - "5050:5050"